// <auto-generated />
using System;
using LabReservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabReservation.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20250520103839_AddLogTable")]
    partial class AddLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("LabReservation.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Labs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Delek1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Delek2"
                        });
                });

            modelBuilder.Entity("LabReservation.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LabId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LabReservation.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "12345",
                            Role = "User",
                            StudentNumber = "2104014"
                        },
                        new
                        {
                            Id = 2,
                            Password = "54321",
                            Role = "User",
                            StudentNumber = "2102709"
                        },
                        new
                        {
                            Id = 3,
                            Password = "33333",
                            Role = "User",
                            StudentNumber = "2104248"
                        },
                        new
                        {
                            Id = 4,
                            Password = "98765",
                            Role = "User",
                            StudentNumber = "2104229"
                        },
                        new
                        {
                            Id = 5,
                            Password = "98765",
                            Role = "User",
                            StudentNumber = "2103094"
                        },
                        new
                        {
                            Id = 6,
                            Password = "98765",
                            Role = "User",
                            StudentNumber = "2103211"
                        },
                        new
                        {
                            Id = 7,
                            Password = "98765",
                            Role = "User",
                            StudentNumber = "2201085"
                        },
                        new
                        {
                            Id = 8,
                            Password = "98765",
                            Role = "User",
                            StudentNumber = "2102184"
                        },
                        new
                        {
                            Id = 9,
                            Password = "98765",
                            Role = "User",
                            StudentNumber = "2103575"
                        },
                        new
                        {
                            Id = 10,
                            Password = "98765",
                            Role = "User",
                            StudentNumber = "2202756"
                        },
                        new
                        {
                            Id = 11,
                            Password = "admin",
                            Role = "Master",
                            StudentNumber = "9999999"
                        });
                });

            modelBuilder.Entity("Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("LabReservation.Models.Reservation", b =>
                {
                    b.HasOne("LabReservation.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabReservation.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
